name: 💡 Feature Request
description: Suggest an idea for this project
title: "[SUGGESTION] "
labels: ["enhancement"]
body:
  - type: textarea
    id: solution
    attributes:
      label: Describe the suggestion that you have
      description: A clear and concise description of what you want to happen. How should it work?
    validations:
      required: true
